# Generated by Django 4.0.5 on 2022-06-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FamiliaresApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiares',
            new_name='Familiar',
        ),
    ]
